// <auto-generated />
namespace Inisra_Web_App_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Almostcompleterenovationafteraddingattributesforall : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Almostcompleterenovationafteraddingattributesforall));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211441321_Almost-complete-renovation-after-adding-attributes-for-all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
